#define _ALT KC_LALT
#define _AMPR IT_AMPR
#define _ASTR IT_ASTR
#define _AT IT_AT
#define _BSLS IT_BSLS
#define _BSPC KC_BSPC
#define _BT BT_HST1
#define _CBC IT_RCBR
#define _CIRC IT_CIRC
#define _CMD KC_LCMD
#define _COLN IT_COLN
#define _COMM IT_COMM
#define _COPY LCMD(KC_C)
#define _CTL KC_LCTL
#define _CUT LCMD(KC_X)
#define _DEL KC_DEL
#define _DLR IT_DLR
#define _DN KC_DOWN
#define _DOT IT_DOT
#define _DQT IT_DQUO
#define _DX KC_RIGHT
#define _END LCMD(KC_RIGHT)
#define _ENT KC_ENT
#define _EQL IT_EQL
#define _ESC KC_ESC
#define _EXLM IT_EXLM
#define _GRV IT_GRV
#define _HASH IT_HASH
#define _HOME LCMD(KC_LEFT)
#define _HR_0 LCMD_T(KC_A)
#define _HR_1 RALT_T(KC_S)
#define _HR_2 LCTL_T(KC_D)
#define _HR_3 LSFT_T(KC_F)
#define _HR_6 RSFT_T(KC_J)
#define _HR_7 RCTL_T(KC_K)
#define _HR_8 RALT_T(KC_L)
#define _HR_9 RCMD_T(_SCLN)
#define _IT_RABK IT_RABK
#define _MEH KC_MEH
#define _MEH_A MEH(KC_A)
#define _MEH_D MEH(KC_D)
#define _MEH_E MEH(KC_E)
#define _MEH_F MEH(KC_F)
#define _MEH_G MEH(KC_G)
#define _MEH_Q MEH(KC_Q)
#define _MEH_R MEH(KC_R)
#define _MEH_S MEH(KC_S)
#define _MEH_T MEH(KC_T)
#define _MEH_T MEH(KC_T)
#define _MEH_W MEH(KC_W)
#define _MINS IT_MINS
#define _MIX MO(MIX)
#define _NO KC_NO
#define _NOR LT(NAV, _SPC)
#define _NUM MO(NUM)
#define _PASTE LCMD(KC_V)
#define _PERC IT_PERC
#define _PGDN KC_PGDN
#define _PGUP KC_PGUP
#define _PIPE IT_PIPE
#define _PLUS IT_PLUS
#define _QUOT IT_QUOT
#define _RBC IT_RPRN
#define _REDO SCMD(KC_Z)
#define _SBC IT_RBRC
#define _SCLN IT_SCLN
#define _SFT KC_LSFT
#define _SLSH IT_SLSH
#define _SPC KC_SPC
#define _SRC LCTL(KC_R)
#define _SX KC_LEFT
#define _T_3 TD(TD_3)
#define _T_E TD(TD_E)
#define _TAB KC_TAB
#define _TILD IT_TILD
#define _TRNS KC_TRNS
#define _UNDO LCMD(KC_Z)
#define _UNDS IT_UNDS
#define _UP KC_UP
#define DEF 0
#define MIX 3
#define NAV 1
#define NUM 2

