#define _ALT KC_LALT
#define _AMPR IT_AMPR
#define _ASTR IT_ASTR
#define _BSPC KC_BSPC
#define _BSLS IT_BSLS
#define _BT BT_HST1
#define _CBC IT_RCBR
#define _CIRC IT_CIRC
#define _CMD KC_LCMD
#define _COLN IT_COLN
#define _COMM IT_COMM
#define _COPY LCMD(KC_C)
#define _CTL KC_LCTL
#define _CUT LCMD(KC_X)
#define _DEL KC_DEL
#define _DLR IT_DLR
#define _DOT IT_DOT
#define _DQT IT_DQUO
#define _END LCMD(KC_RIGHT)
#define _ENT KC_ENT
#define _ESC KC_ESC
#define _EQL IT_EQL
#define _EXLM IT_EXLM
#define _NOR LT(1, _SPC)
#define _NUM MO(2)
#define _GRV IT_GRV
#define _HOME LCMD(KC_LEFT)
#define _HR_0 LCMD_T(KC_A)
#define _HR_1 RALT_T(KC_S)
#define _HR_2 LCTL_T(KC_D)
#define _HR_3 LSFT_T(KC_F)
#define _HR_6 RSFT_T(KC_J)
#define _HR_7 RCTL_T(KC_K)
#define _HR_8 RALT_T(KC_L)
#define _HR_9 RCMD_T(_SCLN)
#define _IT_RABK IT_RABK
#define _MINS IT_MINS
#define _NO KC_NO
#define _PASTE LCMD(KC_V)
#define _PERC IT_PERC
#define _PGDN KC_PGDN
#define _PGUP KC_PGUP
#define _PIPE IT_PIPE
#define _PLUS IT_PLUS
#define _QUOT IT_QUOT
#define _RBC IT_RPRN
#define _REDO SCMD(KC_Z)
#define _SBC IT_RBRC
#define _SCLN IT_SCLN
#define _SFT KC_LSFT
#define _SLSH IT_SLSH
#define _SPC KC_SPC
#define _SRC LCTL(KC_R)
#define _TAB KC_TAB
#define _T_CB TD(TD_CB)
#define _T_DQT TD(TD_DQT)
#define _T_E TD(TD_E)
#define _T_HOME TD(TD_HOME)
#define _T_PERC TD(TD_PERC)
#define _T_PIPE TD(TD_PIPE)
#define _T_QT TD(TD_QT)
#define _T_RB TD(TD_RB)
#define _T_SB TD(TD_SB)
#define _T_SLSH TD(TD_SLSH)
#define _TRNS KC_TRNS
#define _UNDO LCMD(KC_Z)
#define _UNDS IT_UNDS
#define _DN KC_DOWN
#define _DX KC_RIGHT
#define _MEH KC_MEH
#define _SX KC_LEFT
#define _UP KC_UP
