#define TAPPING_TERM        300
// #define QUICK_TAP_TERM      0
#define IGNORE_MOD_TAP_INTERRUPT

#define RETRO_SHIFT

#define AUTO_SHIFT_TIMEOUT  300
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_NUMERIC
